### ISSUE TITLE
Change the proprietary Oracle Java reference to an open source one

### ISSUE THREAD

**Issue by Lezurex** [Anything-Minecraft-Team/anything-minecraft#115]
https://github.com/Anything-Minecraft-Team/anything-minecraft/blob/4167dd48e00d08fc75f5747a200fccace6a61c64/server/guides/other/setup.md#L7

In setup.md, the proprietary Oracle Java is referenced. The Oracle Java is not free to use when used commercially (to gain money with it). Running a minecraft server which is selling ranks would therefore not be allowed with Oracle Java.

I'd recommend referencing the open source and free to use Eclipse Temurin: https://adoptium.net/

In the repository of nearly all Linux distributions, OpenJDK is the default.

**Comment by Kruemmelspalter** [comment]
Good idea, you can change it in your pull request (#114)
