### ISSUE TITLE
Misinformation in server/guides/software/optimizations.md 

### ISSUE THREAD

**Issue by ModdedPro** [Anything-Minecraft-Team/anything-minecraft#123]
Under "FPS - Client Lag" in "optimizations" it says "60+ = Perfect - **Anything over 60 FPS is overkill for Minecraft. Consider capping FPS below 80 to avoid unnecessary stress on hardware.**"

I think that it should be clarified that with a display over 60hz you will see a significant difference in smoothness.

(also the difference between hz and fps should be clarifed)

**Comment by JustDoom** [comment]
Thanks, I will work on fixing this soon
