### ISSUE TITLE
Duplicate USEFUL_PLUGINS

### ISSUE THREAD

**Issue by SidhantUnnithan** [Anything-Minecraft-Team/anything-minecraft#68]
There are two separate files with the same content (minor variations) and it is not very clear as to why. Both of them might be linked from different external files, so one should exercise caution before outright deleting one of them.

The files in question are
- [/info/en_us/USEFUL_PLUGINS.md](https://github.com/Anything-Minecraft-Team/anything-minecraft/blob/main/info/en_us/USEFUL_PLUGINS.md)
- [/info/en_us/PLUGINS/USEFUL_PLUGINS.md](https://github.com/Anything-Minecraft-Team/anything-minecraft/blob/main/info/en_us/PLUGINS/USEFUL_PLUGINS.md)

**Comment by JustDoom** [comment]
I believe that was a mistake, ill fix it soon

**Comment by JustDoom** [comment]
its in pr #69
