### ISSUE TITLE
Naming Conventions for files

### ISSUE THREAD

**Issue by Kruemmelspalter** [Anything-Minecraft-Team/anything-minecraft#7]
I would introduce a naming convention so, for example, the filenames have no spaces and maybe organize them into different subdirs, so the jar things are in a jar directory because with the current PRs we would have to JAR infos in  a directory with the other stuff

**Comment by JustDoom** [comment]
I'll work on this tomorrow, thanks

**Comment by JustDoom** [comment]
i think this is done
