### ISSUE TITLE
Some suggestions for extending this guide

### ISSUE THREAD

**Issue by omit01** [Anything-Minecraft-Team/anything-minecraft#8]
Just a list of some idea's that came up to me:

- Server hosting (self hosting/Minecraft hosting/dedicated VM)
- Server hardware (What's the wecommended amount of dedotated wam/CPU choose)
- Aikars flags and how to read timings reports
- List of widely used/recommended plugins
- Guide on how to build a community/moderation
- Non-Minecraft software such as management panels
- GeyserMC

I know some of these sugggestions are highly debatible or might be out of scope of this guide (is it only server setup or anything about Minecraft server management?). But it's fun to write about.

**Comment by Kruemmelspalter** [comment]
Yeah it would make sense to put the hardware things to another file
management panels would be plugins (wouldn't they?)

**Comment by GhostFace54** [comment]
I'd say that all of these are good recommendations, it's all topics I feel that every newbie should get a good hold of to start his server off on a good note. Only thing that I don't really know that should be of quite much use since I dislike them are management panels as most of them babymode the beginner.

**Comment by omit01** [comment]
On the hardware side i agree with you. Management panels on the other hand are stand-alone pieces of software. Take a look at [Pterodactyl](https://pterodactyl.io/) and [Multicraft](https://www.multicraft.org/).

It's more of the advanced setup and it goes hand in hand with docker and servers. So it should be one of the last things to think about.

**Comment by JustDoom** [comment]
This will be for everything server related, so setting up the panels will be one here, one day hopefully

**Comment by ElMoha943** [comment]
I agree with all but i dont believe geysermc is somethig that a people will look a loot into, i would instead focus more atention into how to build big, secure, networks with bungeecord/waterfall/others. Topics like bungeeguard, anti proxys, antibots, etc. We should also orientate staffs to keep secure their panels and admin credentials, using 2fa and extra securing methods

**Comment by JustDoom** [comment]
> I agree with all but i dont believe geysermc is somethig that people will look a loot into, i would instead focus more atention into how to build big, secure, networks with bungeecord/waterfall/others. Topics like bungeeguard, anti proxys, antibots, etc. We should also orientate staffs to keep secure their panels and admin credentials, using 2fa and extra securing methods

I think we will do that at some point though

**Comment by ElMoha943** [comment]
> > I agree with all but i dont believe geysermc is somethig that people will look a loot into, i would instead focus more atention into how to build big, secure, networks with bungeecord/waterfall/others. Topics like bungeeguard, anti proxys, antibots, etc. We should also orientate staffs to keep secure their panels and admin credentials, using 2fa and extra securing methods
> 
> I think we will do that at some point though

Ofc, the goal would be to cover the most aspects of making a server as we can.

**Comment by Lezurex** [comment]
I created two follow-up issues concerning two of your points which are not yet done. I think you can close it for now.
